# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/prj1.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_2/design_1_axi_iic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_2 || ORIG_REF_NAME==design_1_axi_iic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_5/design_1_ps7_0_axi_periph_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_5 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_5/design_1_rst_ps7_0_100M_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_5 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/boghe/Documents_pc/systemOnChip/DS1086L/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
