set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports d_out_0]
set_property PACKAGE_PIN Y18 [get_ports d_out_0]
set_property PACKAGE_PIN H16 [get_ports clk_in1_0]


set_property IOSTANDARD LVCMOS33 [get_ports pmoda_pin7_io]
set_property IOSTANDARD LVCMOS33 [get_ports pmoda_pin8_io]
set_property IOSTANDARD LVCMOS33 [get_ports pmoda_pin4_io]
set_property IOSTANDARD LVCMOS33 [get_ports pmoda_pin10_io]
set_property IOSTANDARD LVCMOS33 [get_ports pmoda_pin9_io]
set_property PACKAGE_PIN U18 [get_ports pmoda_pin1_io]
set_property PACKAGE_PIN U19 [get_ports pmoda_pin2_io]
set_property PACKAGE_PIN W18 [get_ports pmoda_pin3_io]
set_property PACKAGE_PIN W19 [get_ports pmoda_pin4_io]
set_property PACKAGE_PIN T14 [get_ports pmoda_pin7_io]
set_property PACKAGE_PIN U12 [get_ports pmoda_pin8_io]
set_property PACKAGE_PIN U13 [get_ports pmoda_pin9_io]
set_property PACKAGE_PIN V13 [get_ports pmoda_pin10_io]
set_property PACKAGE_PIN Y18 [get_ports d_out_0]

set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]
set_property PACKAGE_PIN T11 [get_ports IIC_0_scl_io]
set_property PACKAGE_PIN T10 [get_ports IIC_0_sda_io]
